CREATE TABLE IF NOT EXISTS public.fund_raw_sample (
  "c" text,
  "name" text,
  "managers" text,
  "t0" text,
  "t1" text,
  "nav" double precision,
  "nav_date" text,
  "daily_change" double precision,
  "r0w" double precision,
  "r1m" double precision,
  "r3m" double precision,
  "r6m" double precision,
  "r1y" double precision,
  "r2y" double precision,
  "r3y" double precision,
  "r5y" double precision,
  "ytd" double precision,
  "return_launch" text,
  "dd1y" double precision,
  "dd2y" double precision,
  "dd3y" double precision,
  "dd5y" double precision,
  "sr1y" double precision,
  "sr2y" double precision,
  "sr3y" double precision,
  "sr5y" double precision,
  "sg" bigint,
  "fee_orig_pct" double precision,
  "fee_disc_pct" double precision,
  "fund_minsg" text,
  "risk_level" text,
  "perf_avr" text,
  "stock_codes" text,
  "bond_codes" text,
  "top_industry" text,
  "stock_pct" double precision,
  "bond_pct" bigint,
  "cash_pct" double precision,
  "position_est" bigint,
  "scale_change_amt" double precision,
  "inst_pct" double precision,
  "inner_pct" bigint,
  "is_etf" bigint,
  "is_lof" bigint,
  "is_fof" bigint,
  "is_dk" bigint,
  "is_exchange" bigint,
  "q_ret_01" double precision,
  "q_ret_02" double precision,
  "q_ret_03" double precision,
  "q_ret_04" double precision,
  "q_ret_05" double precision,
  "q_ret_06" double precision,
  "q_ret_07" double precision,
  "q_ret_08" double precision,
  "q_ret_09" double precision,
  "q_ret_10" double precision,
  "q_ret_11" double precision,
  "q_ret_12" double precision,
  "q_ret_13" double precision,
  "q_ret_14" double precision,
  "q_ret_15" double precision,
  "q_ret_16" double precision,
  "q_ret_17" double precision,
  "q_ret_18" double precision,
  "q_ret_19" double precision,
  "q_ret_20" double precision,
  "q_ret_21" double precision,
  "q_ret_22" double precision,
  "q_ret_23" double precision,
  "q_ret_24" double precision,
  "q_ret_25" double precision,
  "q_ret_26" double precision,
  "q_ret_27" double precision,
  "q_ret_28" double precision,
  "q_ret_29" double precision,
  "q_ret_30" double precision,
  "q_ret_31" double precision,
  "q_ret_32" double precision,
  "q_ret_33" double precision,
  "q_ret_34" double precision,
  "q_ret_35" double precision,
  "q_ret_36" double precision,
  "q_ret_37" double precision,
  "q_ret_38" double precision,
  "q_ret_39" double precision,
  "q_ret_40" bigint,
  "q_dd_01" double precision,
  "q_dd_02" double precision,
  "q_dd_03" double precision,
  "q_dd_04" double precision,
  "q_dd_05" double precision,
  "q_dd_06" double precision,
  "q_dd_07" double precision,
  "q_dd_08" double precision,
  "q_dd_09" double precision,
  "q_dd_10" double precision,
  "q_dd_11" double precision,
  "q_dd_12" double precision,
  "q_dd_13" double precision,
  "q_dd_14" double precision,
  "q_dd_15" double precision,
  "q_dd_16" double precision,
  "q_dd_17" double precision,
  "q_dd_18" double precision,
  "q_dd_19" double precision,
  "q_dd_20" double precision,
  "q_dd_21" double precision,
  "q_dd_22" double precision,
  "q_dd_23" double precision,
  "q_dd_24" double precision,
  "q_dd_25" double precision,
  "q_dd_26" double precision,
  "q_dd_27" double precision,
  "q_dd_28" double precision,
  "q_dd_29" double precision,
  "q_dd_30" double precision,
  "q_dd_31" double precision,
  "q_dd_32" double precision,
  "q_dd_33" double precision,
  "q_dd_34" double precision,
  "q_dd_35" double precision,
  "q_dd_36" double precision,
  "q_dd_37" double precision,
  "q_dd_38" double precision,
  "q_dd_39" double precision,
  "q_dd_40" double precision,
  "q_sr_01" double precision,
  "q_sr_02" double precision,
  "q_sr_03" double precision,
  "q_sr_04" double precision,
  "q_sr_05" double precision,
  "q_sr_06" double precision,
  "q_sr_07" double precision,
  "q_sr_08" double precision,
  "q_sr_09" double precision,
  "q_sr_10" double precision,
  "q_sr_11" double precision,
  "q_sr_12" double precision,
  "q_sr_13" double precision,
  "q_sr_14" double precision,
  "q_sr_15" double precision,
  "q_sr_16" double precision,
  "q_sr_17" double precision,
  "q_sr_18" double precision,
  "q_sr_19" double precision,
  "q_sr_20" double precision,
  "q_sr_21" double precision,
  "q_sr_22" double precision,
  "q_sr_23" double precision,
  "q_sr_24" double precision,
  "q_sr_25" double precision,
  "q_sr_26" double precision,
  "q_sr_27" double precision,
  "q_sr_28" double precision,
  "q_sr_29" double precision,
  "q_sr_30" double precision,
  "q_sr_31" double precision,
  "q_sr_32" double precision,
  "q_sr_33" double precision,
  "q_sr_34" double precision,
  "q_sr_35" double precision,
  "q_sr_36" double precision,
  "q_sr_37" double precision,
  "q_sr_38" double precision,
  "q_sr_39" double precision,
  "q_sr_40" double precision,
  "q_label_01" text,
  "q_label_02" text,
  "q_label_03" text,
  "q_label_04" text,
  "q_label_05" text,
  "q_label_06" text,
  "q_label_07" text,
  "q_label_08" text,
  "q_label_09" text,
  "q_label_10" text,
  "q_label_11" text,
  "q_label_12" text,
  "q_label_13" text,
  "q_label_14" text,
  "q_label_15" text,
  "q_label_16" text,
  "q_label_17" text,
  "q_label_18" text,
  "q_label_19" text,
  "q_label_20" text,
  "q_label_21" text,
  "q_label_22" text,
  "q_label_23" text,
  "q_label_24" text,
  "q_label_25" text,
  "q_label_26" text,
  "q_label_27" text,
  "q_label_28" text,
  "q_label_29" text,
  "q_label_30" text,
  "q_label_31" text,
  "q_label_32" text,
  "q_label_33" text,
  "q_label_34" text,
  "q_label_35" text,
  "q_label_36" text,
  "q_label_37" text,
  "q_label_38" text,
  "q_label_39" text,
  "q_label_40" text,
  "score_1y" double precision,
  "score_2y" double precision,
  "score_3y" double precision,
  "score_5y" double precision,
  "score_7y" bigint,
  "score_10y" double precision
);

-- Enable RLS
ALTER TABLE public.fund_raw_sample ENABLE ROW LEVEL SECURITY;

-- Allow anon SELECT
CREATE POLICY "anon_select_fund_raw_sample" ON public.fund_raw_sample
  FOR SELECT USING (true);

-- Allow anon INSERT/UPDATE/DELETE
CREATE POLICY "anon_all_fund_raw_sample" ON public.fund_raw_sample
  FOR ALL USING (true);
